export const GAME_STATE = {
  HERO_SELECTION: "HERO_SELECTION",
  STRATEGY_TIME: "STRATEGY_TIME",
  PRE_GAME: "PRE_GAME",
  GAME_IN_PROGRESS: "GAME_IN_PROGRESS",
  POST_GAME: "POST_GAME",
};

export const TICK_RATE = 1000 * 1;
